development:
  adapter: postgresql
  encoding: utf8
  database: popr_development
  pool: 5


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: popr_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: popr_production
  pool: 5
