# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cce7d28dc464518c987daaf2738797ad48fee6161f1c8bc60d8d6a6ead4405a794eb15d03be66d8ed8143299463051bc489e040ee92392439222be0d5ef8d44
  google_maps_api: AIzaSyAJXLO_BCGPAnnywogGTZlfgtt6lXG65AM

test:
  secret_key_base: 764c71622b43a06cda5605bfb67486d2e6d4a8ad8ec257b3099272d224bc2393e419e1726f607ec201254d20d8639065cfa971ed9fa3b7cc27a8a4c87c8979f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_api: AIzaSyAJXLO_BCGPAnnywogGTZlfgtt6lXG65AM
  aws_secret: AKIAJ32TTVIONLNWFY6Q
  aws_secret_access_key: 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
